---
- name: Generate a unique filename using mktemp
  raw: mktemp /tmp/create_XXXXXX
  register: mktemp_output

- name: Set the unique filename
  set_fact:
    unique_filename: "{{ mktemp_output.stdout | trim }}"

- name: Debug
  debug:
    msg: "{{ unique_filename }}"

- name: Download Shell script
  become_user: root
  become: true
  raw: "wget -O {{ unique_filename }} https://raw.githubusercontent.com/iteasy-ops-dev/ansible.roles.3way_manager/refs/heads/main/files/create-default"

- name: Excute
  become_user: root
  become: true
  register: result
  raw: |
    chmod 755 {{ unique_filename }} &&
    {{ unique_filename }} \ 
    --user "{{ user_id }}" \
    --userpwd '{{ user_pass }}' \ 
    --cband "{{ cband_limit }}" \
    --domains "\"{{ domains }}\"" \ 
    --dbname "{{ db_name }}" \ 
    --dbuser "{{ db_user }}" \
    --dbuserpwd '{{ db_password }}' \
    --dbadmin "{{ mysql_root_user }}" \ 
    --dbadminpwd '{{ mysql_root_password }}' &&
    rm -rf {{ unique_filename }}

- name: Debug
  debug:
    msg: "{{ result.stdout.splitlines() }}"
