---
# tasks file for iteasy.ansible.roles.3way_manager
- name: Check Server
  raw: "uname -a | grep -oP 'el\\K[0-9]+'"
  register: result
  
- name: Debug Server OS version
  debug:
    msg: "OS version is el{{ result.stdout }}"

- name: Do something if OS version is el7
  debug:
    msg: "This is EL7"
  when: result.stdout == "7"

- name: Do something else if OS version is el8
  debug:
    msg: "This is EL8"
  when: result.stdout == "8"

- name: Fallback for other versions
  debug:
    msg: "This is not EL7 or EL8"
  when: result.stdout not in ["7", "8"]

# - name: Include setup-raw-based tasks
#   ansible.builtin.include_tasks: "setup-raw-task.yml"
#   when: setup | default(true) | bool

# - name: Include remove-raw-based tasks
#   ansible.builtin.include_tasks: "remove-raw-task.yml"
#   when: setup is defined and not setup | bool


