---
# tasks file for iteasy.ansible.roles.3way_manager
- name: Check Server OS version
  raw: "curl -s ifconfig.me | cut -d'.' -f4"
  register: result

- name: Debug Server OS version (after trim)
  debug:
    msg: "{{ result.stdout | trim }}"


# - name: Include setup-raw-based tasks
#   ansible.builtin.include_tasks: "setup-raw-task.yml"
#   when: setup | default(true) | bool

# - name: Include remove-raw-based tasks
#   ansible.builtin.include_tasks: "remove-raw-task.yml"
#   when: setup is defined and not setup | bool


