---
# tasks file for iteasy.ansible.roles.3way_manager
- name: Generate a random string for filename
  set_fact:
    random_suffix: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"

- name: Create unique filename using random string
  set_fact:
    unique_filename: "/tmp/remove_{{ random_suffix }}"

- name: Download Shell script
  become_user: root
  become: true
  raw: "wget -O {{ unique_filename }} https://raw.githubusercontent.com/iteasy-ops-dev/ansible.roles.3way_manager/refs/heads/main/files/remove-default"
  register: result

- name: Excute
  become_user: root
  become: true
  register: result
  raw: |
    chmod 755 {{ unique_filename }}
    {{ unique_filename }} {{ user_id }} {{ db_name }} {{ db_user }} {{ mysql_root_user }} '{{ mysql_root_password }}'
    rm -rf {{ unique_filename }}

- name: Debug
  debug:
    msg: "{{ result.stdout.splitlines() }}"