---
# tasks file for iteasy.ansible.roles.3way_manager
- name: Copy the shell script to remote server
  copy:
    src: files/remove-26           # 로컬에 있는 쉘 스크립트 경로
    dest: /tmp/remove           # 원격 서버에 전송될 경로
    mode: '0755'                # 실행 권한 설정

- name: Excute
  become_user: root
  become: true
  register: result
  raw: |
    /tmp/remove {{ user_id }} {{ db_name }} {{ db_user }} {{ mysql_root_user }} '{{ mysql_root_password }}'
    rm -rf /tmp/remove

- name: Debug
  debug:
    msg: "{{ result.stdout.splitlines() }}"

- name: Check for script failure
  fail:
    msg: "The script encountered an error: {{ result.stdout }}"
  when: result.rc != 0