---
# tasks file for iteasy.ansible.roles.3way_manager
# - name: Generate a random string for filename
#   set_fact:
#     random_suffix: "{{ lookup('password', '/dev/null length=32 chars=ascii_letters') }}"

# - name: Create unique filename using random string
#   set_fact:
#     unique_filename: "/tmp/create_{{ random_suffix }}"

- name: Generate a unique filename using mktemp
  raw: mktemp /tmp/create_XXXXXX
  register: mktemp_output

- name: Set the unique filename
  set_fact:
    unique_filename: "{{ mktemp_output.stdout | trim }}"
- name: Download Shell script
  become_user: root
  become: true
  raw: "wget -O {{ unique_filename }} https://raw.githubusercontent.com/iteasy-ops-dev/ansible.roles.3way_manager/refs/heads/main/files/create-232"

- name: Excute
  become_user: root
  become: true
  register: result
  raw: |
    chmod 755 {{ unique_filename }}
    {{ unique_filename }} {{ user_id }} {{ user_pass }} {{ db_name }} {{ db_user }} '{{ db_password }}' {{ mysql_root_user }} '{{ mysql_root_password }}'
    rm -rf {{ unique_filename }}

- name: Debug
  debug:
    msg: "{{ result.stdout.splitlines() }}"

- name: Check for script failure
  fail:
    msg: "The script encountered an error: {{ result.stdout }}"
  when: result.rc != 0 or 'exit 1' in result.stdout