---
# tasks file for iteasy.ansible.roles.3way_manager
- name: Generate a random string for filename
  set_fact:
    random_suffix: "{{ lookup('pipe', 'uuidgen') | regex_replace('-', '') }}"

- name: Create unique filename using random string
  set_fact:
    unique_filename: "/tmp/create_{{ random_suffix }}"

- name: Download Shell script
  become_user: root
  become: true
  raw: "wget -O {{ unique_filename }} https://raw.githubusercontent.com/iteasy-ops-dev/ansible.roles.3way_manager/refs/heads/main/files/create-default"

- name: Excute
  become_user: root
  become: true
  register: result
  raw: |
    chmod 755 {{ unique_filename }}
    {{ unique_filename }} {{ user_id }} {{ user_pass }} {{ db_name }} {{ db_user }} '{{ db_password }}' {{ mysql_root_user }} '{{ mysql_root_password }}'
    rm -rf {{ unique_filename }}

- name: Debug
  debug:
    msg: "{{ result.stdout.splitlines() }}"