---
# tasks file for iteasy.ansible.roles.3way_manager
- name: Copy the shell script to remote server
  copy:
    src: update-cband-26           # 로컬에 있는 쉘 스크립트 경로
    dest: /tmp/update-cband           # 원격 서버에 전송될 경로
    mode: '0755'                              # 실행 권한 설정

- name: Excute
  become_user: root
  become: true
  register: result
  raw: |
    /tmp/update-cband {{ user_id }} {{ cband_limit }}
    rm -rf /tmp/update-cband

- name: Debug
  debug:
    msg: "{{ result.stdout.splitlines() }}"
