---
# tasks file for iteasy.ansible.roles.3way_manager
- name: Generate a unique filename using mktemp
  raw: mktemp /tmp/remove_XXXXXX
  register: mktemp_output

- name: Set the unique filename
  set_fact:
    unique_filename: "{{ mktemp_output.stdout | trim }}"
- name: Download Shell script
  become_user: root
  become: true
  raw: "wget -O {{ unique_filename }} https://raw.githubusercontent.com/iteasy-ops-dev/ansible.roles.3way_manager/refs/heads/main/files/update-cband-default"
  register: result

- name: Excute
  become_user: root
  become: true
  register: result
  raw: |
    chmod 755 {{ unique_filename }}
    {{ unique_filename }} {{ user_id }} {{ db_name }} {{ db_user }} {{ mysql_root_user }} '{{ mysql_root_password }}'
    rm -rf {{ unique_filename }}

- name: Debug
  debug:
    msg: "{{ result.stdout.splitlines() }}"
